export interface AITool {
  id: string;
  name: string;
  description: string;
  category: string;
  pricing: 'Free' | 'Freemium' | 'Paid';
  rating: number;
  users: string;
  features: string[];
  imageUrl?: string;
  website?: string;
}

export const categories = [
  'All',
  'Writing',
  'Design',
  'Development',
  'Analytics',
  'Marketing',
  'Productivity',
  'Image Generation',
  'Video',
  'Audio',
  'Chatbots',
  'Research',
  'Education',
  'Customer Support',
  'Finance',
  'Healthcare',
];

export const aiTools: AITool[] = [
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    description: 'Conversational AI assistant that helps with writing, coding, analysis, and creative tasks.',
    category: 'Writing',
    pricing: 'Freemium',
    rating: 4.8,
    users: '100M+',
    features: ['Natural language processing', 'Code generation', 'Content creation', 'Data analysis'],
  },
  {
    id: 'midjourney',
    name: 'Midjourney',
    description: 'AI-powered image generation tool that creates stunning artwork from text descriptions.',
    category: 'Image Generation',
    pricing: 'Paid',
    rating: 4.7,
    users: '15M+',
    features: ['Text-to-image', 'High resolution', 'Style variations', 'Commercial use'],
  },
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    description: 'AI pair programmer that helps you write code faster with intelligent suggestions.',
    category: 'Development',
    pricing: 'Paid',
    rating: 4.6,
    users: '10M+',
    features: ['Code completion', 'Multi-language support', 'Context-aware', 'IDE integration'],
  },
  {
    id: 'jasper',
    name: 'Jasper',
    description: 'AI writing assistant for creating marketing copy, blog posts, and social media content.',
    category: 'Marketing',
    pricing: 'Paid',
    rating: 4.5,
    users: '100K+',
    features: ['SEO optimization', 'Templates', 'Brand voice', 'Plagiarism check'],
  },
  {
    id: 'tableau-gpt',
    name: 'Tableau GPT',
    description: 'AI-powered analytics tool that turns data into actionable insights with natural language.',
    category: 'Analytics',
    pricing: 'Freemium',
    rating: 4.4,
    users: '5M+',
    features: ['Data visualization', 'Natural language queries', 'Automated insights', 'Dashboard creation'],
  },
  {
    id: 'canva-ai',
    name: 'Canva AI',
    description: 'Design platform with AI tools for creating graphics, presentations, and marketing materials.',
    category: 'Design',
    pricing: 'Freemium',
    rating: 4.7,
    users: '135M+',
    features: ['Magic design', 'Background remover', 'Text-to-image', 'Templates'],
  },
  {
    id: 'grammarly',
    name: 'Grammarly',
    description: 'AI writing assistant that helps improve grammar, clarity, and writing style.',
    category: 'Writing',
    pricing: 'Freemium',
    rating: 4.6,
    users: '30M+',
    features: ['Grammar check', 'Tone detection', 'Plagiarism detection', 'Style suggestions'],
  },
  {
    id: 'notion-ai',
    name: 'Notion AI',
    description: 'AI-powered workspace that helps with writing, brainstorming, and organizing information.',
    category: 'Productivity',
    pricing: 'Freemium',
    rating: 4.5,
    users: '30M+',
    features: ['Content generation', 'Summarization', 'Translation', 'Action items'],
  },
  {
    id: 'runway',
    name: 'Runway',
    description: 'AI-powered video editing and generation tool for creative professionals.',
    category: 'Video',
    pricing: 'Freemium',
    rating: 4.6,
    users: '8M+',
    features: ['Video generation', 'Green screen', 'Motion tracking', 'Style transfer'],
  },
  {
    id: 'murf-ai',
    name: 'Murf AI',
    description: 'AI voice generator for creating realistic voiceovers in multiple languages.',
    category: 'Audio',
    pricing: 'Freemium',
    rating: 4.4,
    users: '4M+',
    features: ['Text-to-speech', 'Voice cloning', 'Multi-language', 'Emotion control'],
  },
  {
    id: 'copy-ai',
    name: 'Copy.ai',
    description: 'AI copywriting tool that generates marketing copy, product descriptions, and more.',
    category: 'Marketing',
    pricing: 'Freemium',
    rating: 4.5,
    users: '10M+',
    features: ['Templates', 'Tone selection', 'Multi-language', 'Long-form content'],
  },
  {
    id: 'stable-diffusion',
    name: 'Stable Diffusion',
    description: 'Open-source AI model for generating high-quality images from text descriptions.',
    category: 'Image Generation',
    pricing: 'Free',
    rating: 4.5,
    users: '12M+',
    features: ['Text-to-image', 'Image-to-image', 'Open source', 'Customizable'],
  },
  {
    id: 'claude',
    name: 'Claude',
    description: 'AI assistant focused on helpful, harmless, and honest conversations.',
    category: 'Writing',
    pricing: 'Freemium',
    rating: 4.7,
    users: '5M+',
    features: ['Long context', 'Code analysis', 'Document processing', 'Creative writing'],
  },
  {
    id: 'adobe-firefly',
    name: 'Adobe Firefly',
    description: 'Generative AI for creative workflows, integrated into Adobe Creative Cloud.',
    category: 'Design',
    pricing: 'Freemium',
    rating: 4.6,
    users: '15M+',
    features: ['Text effects', 'Generative fill', 'Vector recolor', 'Commercial safe'],
  },
  {
    id: 'zapier-ai',
    name: 'Zapier AI',
    description: 'Automation platform with AI to connect apps and automate workflows.',
    category: 'Productivity',
    pricing: 'Freemium',
    rating: 4.5,
    users: '5M+',
    features: ['Workflow automation', 'App integration', 'AI suggestions', 'No-code'],
  },
  {
    id: 'synthesia',
    name: 'Synthesia',
    description: 'AI video generation platform for creating professional videos with AI avatars.',
    category: 'Video',
    pricing: 'Paid',
    rating: 4.5,
    users: '2M+',
    features: ['AI avatars', 'Multi-language', 'No filming', 'Custom avatars'],
  },
  // Chatbots
  {
    id: 'intercom-fin',
    name: 'Intercom Fin',
    description: 'AI chatbot powered by GPT-4 that resolves customer queries instantly without human agents.',
    category: 'Chatbots',
    pricing: 'Paid',
    rating: 4.6,
    users: '25K+',
    features: ['GPT-4 powered', 'Instant resolution', 'Handoff to humans', 'Multi-channel'],
  },
  {
    id: 'tidio',
    name: 'Tidio',
    description: 'Live chat and AI chatbot platform for ecommerce businesses to boost conversions and support.',
    category: 'Chatbots',
    pricing: 'Freemium',
    rating: 4.4,
    users: '300K+',
    features: ['AI chatbot', 'Live chat', 'Email automation', 'Ecommerce integrations'],
  },
  // Research
  {
    id: 'elicit',
    name: 'Elicit',
    description: 'AI research assistant that finds and summarizes academic papers to accelerate literature reviews.',
    category: 'Research',
    pricing: 'Freemium',
    rating: 4.5,
    users: '1M+',
    features: ['Paper search', 'Auto-summarization', 'Data extraction', 'Citation export'],
  },
  {
    id: 'perplexity',
    name: 'Perplexity AI',
    description: 'AI-powered search engine that answers complex questions with cited, real-time sources.',
    category: 'Research',
    pricing: 'Freemium',
    rating: 4.7,
    users: '10M+',
    features: ['Real-time search', 'Source citations', 'Follow-up questions', 'File upload'],
  },
  // Education
  {
    id: 'khanmigo',
    name: 'Khanmigo',
    description: 'AI tutor by Khan Academy that guides students through problems with Socratic questioning.',
    category: 'Education',
    pricing: 'Paid',
    rating: 4.5,
    users: '500K+',
    features: ['Socratic method', 'Math tutoring', 'Writing coach', 'Safe for students'],
  },
  {
    id: 'duolingo-max',
    name: 'Duolingo Max',
    description: 'AI-enhanced language learning with GPT-4 powered conversation practice and explanations.',
    category: 'Education',
    pricing: 'Paid',
    rating: 4.6,
    users: '3M+',
    features: ['Roleplay conversations', 'Mistake explanations', 'Adaptive lessons', '40+ languages'],
  },
  // Customer Support
  {
    id: 'zendesk-ai',
    name: 'Zendesk AI',
    description: 'AI layer on top of Zendesk that triages tickets, suggests replies, and automates resolutions.',
    category: 'Customer Support',
    pricing: 'Paid',
    rating: 4.5,
    users: '100K+',
    features: ['Ticket triage', 'Reply suggestions', 'Sentiment analysis', 'Auto-routing'],
  },
  {
    id: 'freshdesk-freddy',
    name: 'Freddy AI',
    description: 'Freshdesk\'s AI engine for automating support workflows and delivering self-service answers.',
    category: 'Customer Support',
    pricing: 'Freemium',
    rating: 4.3,
    users: '60K+',
    features: ['Self-service bots', 'Agent assist', 'Predictive routing', 'Canned responses'],
  },
  // Finance
  {
    id: 'trueaccord',
    name: 'Navan AI',
    description: 'AI-powered spend management platform that automates expense reports and policy compliance.',
    category: 'Finance',
    pricing: 'Paid',
    rating: 4.4,
    users: '8K+',
    features: ['Expense automation', 'Policy enforcement', 'Receipt capture', 'Real-time reporting'],
  },
  {
    id: 'domo-ai',
    name: 'Domo AI',
    description: 'Business intelligence platform with AI that surfaces financial insights and forecasts from data.',
    category: 'Finance',
    pricing: 'Paid',
    rating: 4.3,
    users: '3K+',
    features: ['Financial dashboards', 'Predictive forecasts', 'Anomaly detection', 'Natural language queries'],
  },
  // Healthcare
  {
    id: 'nuance-dax',
    name: 'Nuance DAX',
    description: 'AI clinical documentation assistant that automatically captures patient-physician conversations.',
    category: 'Healthcare',
    pricing: 'Paid',
    rating: 4.7,
    users: '550K+',
    features: ['Auto-documentation', 'EHR integration', 'HIPAA compliant', 'Ambient AI'],
  },
  {
    id: 'glass-health',
    name: 'Glass Health',
    description: 'AI clinical decision support tool that generates differential diagnoses and care plans.',
    category: 'Healthcare',
    pricing: 'Freemium',
    rating: 4.5,
    users: '200K+',
    features: ['Differential diagnosis', 'Care plan generation', 'Evidence-based', 'Clinical notes'],
  },

  // ── Writing ──────────────────────────────────────────────────────────────
  {
    id: 'writesonic',
    name: 'Writesonic',
    description: 'AI writing platform for generating SEO-optimised articles, ads, and landing page copy at scale.',
    category: 'Writing',
    pricing: 'Freemium',
    rating: 4.4,
    users: '4M+',
    features: ['Blog articles', 'Ad copy', 'Paraphraser', 'SEO integration'],
  },
  {
    id: 'rytr',
    name: 'Rytr',
    description: 'Budget-friendly AI writing assistant that generates content in 40+ languages and 20+ tones.',
    category: 'Writing',
    pricing: 'Freemium',
    rating: 4.3,
    users: '7M+',
    features: ['40+ languages', '20+ tones', 'Plagiarism checker', 'Chrome extension'],
  },
  {
    id: 'quillbot',
    name: 'QuillBot',
    description: 'AI paraphrasing and summarisation tool that rewrites text while preserving original meaning.',
    category: 'Writing',
    pricing: 'Freemium',
    rating: 4.5,
    users: '35M+',
    features: ['Paraphraser', 'Summariser', 'Grammar checker', 'Citation generator'],
  },
  {
    id: 'sudowrite',
    name: 'Sudowrite',
    description: 'AI writing partner built for fiction authors, helping with story beats, descriptions, and dialogue.',
    category: 'Writing',
    pricing: 'Paid',
    rating: 4.4,
    users: '100K+',
    features: ['Story generation', 'Character voices', 'Sensory descriptions', 'Feedback mode'],
  },
  {
    id: 'hyperwrite',
    name: 'HyperWrite',
    description: 'Personal AI writing assistant that learns your style and autocompletes sentences as you type.',
    category: 'Writing',
    pricing: 'Freemium',
    rating: 4.3,
    users: '500K+',
    features: ['Autocomplete', 'Style learning', 'Research assistant', 'Email drafts'],
  },
  {
    id: 'wordtune',
    name: 'Wordtune',
    description: 'AI rewriting tool that offers alternative phrasings to make writing clearer and more engaging.',
    category: 'Writing',
    pricing: 'Freemium',
    rating: 4.4,
    users: '10M+',
    features: ['Rewrite suggestions', 'Shorten/expand', 'Tone adjustment', 'Translation'],
  },
  {
    id: 'hemingway-app',
    name: 'Hemingway Editor',
    description: 'AI-assisted writing editor that highlights complex sentences and passive voice to improve readability.',
    category: 'Writing',
    pricing: 'Freemium',
    rating: 4.3,
    users: '1M+',
    features: ['Readability score', 'Sentence highlighting', 'Passive voice detection', 'Desktop app'],
  },
  {
    id: 'anyword',
    name: 'Anyword',
    description: 'Predictive AI writing platform that scores copy for conversion performance before publishing.',
    category: 'Writing',
    pricing: 'Paid',
    rating: 4.4,
    users: '1M+',
    features: ['Performance score', 'Audience targeting', 'A/B variants', 'Data-driven copy'],
  },
  {
    id: 'ink-editor',
    name: 'INK Editor',
    description: 'SEO-focused AI writing assistant that optimises content in real time for search ranking.',
    category: 'Writing',
    pricing: 'Freemium',
    rating: 4.2,
    users: '500K+',
    features: ['SEO optimisation', 'AI outline', 'Readability', 'Keyword suggestions'],
  },
  {
    id: 'longshot-ai',
    name: 'LongShot AI',
    description: 'Fact-checked AI writing tool designed for producing accurate long-form blog content.',
    category: 'Writing',
    pricing: 'Freemium',
    rating: 4.1,
    users: '200K+',
    features: ['Fact checking', 'Long-form blogs', 'SEO templates', 'Plagiarism check'],
  },
  {
    id: 'lex',
    name: 'Lex',
    description: 'Minimalist AI writing tool that unblocks writers with inline suggestions and feedback.',
    category: 'Writing',
    pricing: 'Paid',
    rating: 4.2,
    users: '150K+',
    features: ['Inline AI suggestions', 'Focus mode', 'Feedback requests', 'Publishing'],
  },
  {
    id: 'peppertype',
    name: 'Peppertype AI',
    description: 'Content generation engine producing ads, emails, and product descriptions in seconds.',
    category: 'Writing',
    pricing: 'Paid',
    rating: 4.1,
    users: '80K+',
    features: ['50+ content types', 'Brand voice', 'Team workspace', 'API access'],
  },

  // ── Design ────────────────────────────────────────────────────────────────
  {
    id: 'uizard',
    name: 'Uizard',
    description: 'AI design tool that converts hand-drawn sketches and text prompts into interactive UI mockups.',
    category: 'Design',
    pricing: 'Freemium',
    rating: 4.3,
    users: '500K+',
    features: ['Sketch-to-UI', 'Text-to-mockup', 'Autodesigner', 'Collaboration'],
  },
  {
    id: 'looka',
    name: 'Looka',
    description: 'AI logo and brand identity generator that creates professional logos from a style quiz.',
    category: 'Design',
    pricing: 'Paid',
    rating: 4.4,
    users: '20M+',
    features: ['Logo generation', 'Brand kit', 'Business card', 'Social assets'],
  },
  {
    id: 'khroma',
    name: 'Khroma',
    description: 'AI colour palette tool that learns your preferences and generates infinite on-brand palettes.',
    category: 'Design',
    pricing: 'Free',
    rating: 4.3,
    users: '300K+',
    features: ['Personalised palettes', 'Colour search', 'Typography pairings', 'Export'],
  },
  {
    id: 'remove-bg',
    name: 'Remove.bg',
    description: 'AI background remover that instantly strips backgrounds from photos with a single click.',
    category: 'Design',
    pricing: 'Freemium',
    rating: 4.6,
    users: '30M+',
    features: ['1-click removal', 'Batch processing', 'API access', 'HD downloads'],
  },
  {
    id: 'magician-figma',
    name: 'Magician for Figma',
    description: 'AI design plugin for Figma that generates icons, copy, and imagery directly in your design file.',
    category: 'Design',
    pricing: 'Paid',
    rating: 4.2,
    users: '100K+',
    features: ['Icon generation', 'Copy suggestions', 'Image creation', 'Figma native'],
  },
  {
    id: 'visily',
    name: 'Visily',
    description: 'AI-powered wireframing tool that turns screenshots or text into editable wireframes instantly.',
    category: 'Design',
    pricing: 'Freemium',
    rating: 4.3,
    users: '200K+',
    features: ['Screenshot-to-wireframe', 'Template library', 'Team collaboration', 'Export'],
  },
  {
    id: 'galileo-ai',
    name: 'Galileo AI',
    description: 'Generates high-fidelity UI designs from a text description in seconds.',
    category: 'Design',
    pricing: 'Paid',
    rating: 4.3,
    users: '50K+',
    features: ['Text-to-UI', 'Component library', 'Figma export', 'Fast iteration'],
  },
  {
    id: 'designify',
    name: 'Designify',
    description: 'AI photo editor that removes backgrounds and adds professional-looking design elements automatically.',
    category: 'Design',
    pricing: 'Freemium',
    rating: 4.1,
    users: '500K+',
    features: ['Background removal', 'Auto-enhance', 'Shadows', 'Batch edit'],
  },
  {
    id: 'colormind',
    name: 'Colormind',
    description: 'AI colour scheme generator trained on real designs to produce aesthetically pleasing palettes.',
    category: 'Design',
    pricing: 'Free',
    rating: 4.0,
    users: '200K+',
    features: ['Bootstrap themes', 'Locked colours', 'Movie palette extraction', 'API'],
  },
  {
    id: 'fontjoy',
    name: 'Fontjoy',
    description: 'Deep-learning font pairing tool that generates harmonious Google Fonts combinations instantly.',
    category: 'Design',
    pricing: 'Free',
    rating: 4.2,
    users: '500K+',
    features: ['Font pairing', 'Contrast control', 'Lock fonts', 'Google Fonts'],
  },
  {
    id: 'autodraw',
    name: 'AutoDraw',
    description: 'Google AI drawing tool that predicts what you are trying to draw and suggests clean vector icons.',
    category: 'Design',
    pricing: 'Free',
    rating: 4.0,
    users: '5M+',
    features: ['Drawing prediction', 'Vector icons', 'Free to use', 'Browser-based'],
  },
  {
    id: 'diagram-ai',
    name: 'Diagram',
    description: 'AI-powered design toolkit for product teams, featuring smart components and generative UI.',
    category: 'Design',
    pricing: 'Freemium',
    rating: 4.2,
    users: '80K+',
    features: ['Smart components', 'Generative UI', 'Figma plugin', 'Design tokens'],
  },

  // ── Development ───────────────────────────────────────────────────────────
  {
    id: 'tabnine',
    name: 'Tabnine',
    description: 'AI code completion assistant that works across all major IDEs and keeps code private on-premise.',
    category: 'Development',
    pricing: 'Freemium',
    rating: 4.4,
    users: '1M+',
    features: ['Full-line completion', 'Private deployment', '30+ languages', 'Team learning'],
  },
  {
    id: 'codeium',
    name: 'Codeium',
    description: 'Free AI coding assistant with autocomplete, chat, and search across your codebase.',
    category: 'Development',
    pricing: 'Freemium',
    rating: 4.5,
    users: '1M+',
    features: ['Autocomplete', 'AI chat', 'Codebase search', '70+ languages'],
  },
  {
    id: 'cursor-ide',
    name: 'Cursor',
    description: 'AI-first code editor built on VS Code that lets you write, edit, and debug with natural language.',
    category: 'Development',
    pricing: 'Freemium',
    rating: 4.7,
    users: '500K+',
    features: ['Natural language editing', 'Codebase chat', 'Diff preview', 'VS Code compatible'],
  },
  {
    id: 'replit-ghostwriter',
    name: 'Replit Ghostwriter',
    description: 'AI coding assistant embedded in Replit that generates, explains, and debugs code in the browser.',
    category: 'Development',
    pricing: 'Freemium',
    rating: 4.3,
    users: '3M+',
    features: ['In-browser coding', 'Code explanation', 'Debugging', 'Deployment'],
  },
  {
    id: 'amazon-codewhisperer',
    name: 'Amazon CodeWhisperer',
    description: 'AWS AI coding companion with security scanning and reference tracking for enterprise teams.',
    category: 'Development',
    pricing: 'Freemium',
    rating: 4.3,
    users: '500K+',
    features: ['Security scanning', 'Reference tracking', 'AWS optimised', '15 languages'],
  },
  {
    id: 'sourcegraph-cody',
    name: 'Sourcegraph Cody',
    description: 'AI coding assistant with deep codebase context that understands your entire repository.',
    category: 'Development',
    pricing: 'Freemium',
    rating: 4.4,
    users: '200K+',
    features: ['Codebase context', 'Multi-repo search', 'Inline chat', 'Enterprise security'],
  },
  {
    id: 'pieces-ai',
    name: 'Pieces for Developers',
    description: 'AI-powered developer productivity tool for capturing, enriching, and reusing code snippets.',
    category: 'Development',
    pricing: 'Freemium',
    rating: 4.3,
    users: '100K+',
    features: ['Snippet capture', 'Context enrichment', 'Offline AI', 'IDE plugins'],
  },
  {
    id: 'codegpt',
    name: 'CodeGPT',
    description: 'VS Code extension bringing multiple AI models directly into your editor for code assistance.',
    category: 'Development',
    pricing: 'Freemium',
    rating: 4.2,
    users: '300K+',
    features: ['Multi-model support', 'Chat in editor', 'Code generation', 'Explanation'],
  },
  {
    id: 'gpt-engineer',
    name: 'GPT Engineer',
    description: 'Open-source AI agent that builds entire codebases from a single natural language specification.',
    category: 'Development',
    pricing: 'Free',
    rating: 4.2,
    users: '50K+',
    features: ['Full app generation', 'Open source', 'Iterative refinement', 'CLI-based'],
  },
  {
    id: 'debuild',
    name: 'Debuild',
    description: 'Low-code AI tool that generates React components and SQL queries from plain English descriptions.',
    category: 'Development',
    pricing: 'Freemium',
    rating: 4.0,
    users: '30K+',
    features: ['React generation', 'SQL generation', 'Visual editor', 'Fast prototyping'],
  },
  {
    id: 'mintlify',
    name: 'Mintlify',
    description: 'AI documentation writer that automatically generates docs from code and keeps them up to date.',
    category: 'Development',
    pricing: 'Freemium',
    rating: 4.4,
    users: '5K+',
    features: ['Auto docs', 'Code sync', 'Beautiful UI', 'API reference'],
  },
  {
    id: 'safurai',
    name: 'Safurai',
    description: 'AI coding assistant focused on security, helping developers write safer code and spot vulnerabilities.',
    category: 'Development',
    pricing: 'Freemium',
    rating: 4.1,
    users: '80K+',
    features: ['Security focus', 'Vulnerability detection', 'Code review', 'Multi-language'],
  },

  // ── Analytics ─────────────────────────────────────────────────────────────
  {
    id: 'obvious-ai',
    name: 'Obviously AI',
    description: 'No-code predictive analytics platform that builds and deploys ML models in minutes.',
    category: 'Analytics',
    pricing: 'Paid',
    rating: 4.3,
    users: '10K+',
    features: ['No-code ML', 'Predictions', 'CSV upload', 'API deployment'],
  },
  {
    id: 'polymer-search',
    name: 'Polymer',
    description: 'AI business intelligence tool that turns spreadsheets into interactive dashboards with zero SQL.',
    category: 'Analytics',
    pricing: 'Freemium',
    rating: 4.2,
    users: '50K+',
    features: ['No-SQL insights', 'Auto dashboards', 'Anomaly alerts', 'Team sharing'],
  },
  {
    id: 'julius-ai',
    name: 'Julius AI',
    description: 'AI data analyst that lets you chat with your data files and get instant charts and insights.',
    category: 'Analytics',
    pricing: 'Freemium',
    rating: 4.5,
    users: '200K+',
    features: ['Chat with data', 'Chart generation', 'Statistical analysis', 'Python execution'],
  },
  {
    id: 'akkio',
    name: 'Akkio',
    description: 'AI analytics platform for agencies and enterprises to predict outcomes and create AI workflows.',
    category: 'Analytics',
    pricing: 'Paid',
    rating: 4.3,
    users: '20K+',
    features: ['Predictive models', 'CRM integration', 'Chat data exploration', 'White-label'],
  },
  {
    id: 'datarobot',
    name: 'DataRobot',
    description: 'Enterprise AI platform for building, deploying, and monitoring machine learning models at scale.',
    category: 'Analytics',
    pricing: 'Paid',
    rating: 4.4,
    users: '80K+',
    features: ['AutoML', 'Model monitoring', 'MLOps', 'Explainable AI'],
  },
  {
    id: 'pecan-ai',
    name: 'Pecan AI',
    description: 'Predictive analytics platform for business analysts, no data science background required.',
    category: 'Analytics',
    pricing: 'Paid',
    rating: 4.2,
    users: '5K+',
    features: ['SQL-based ML', 'Churn prediction', 'LTV modelling', 'Business metrics'],
  },
  {
    id: 'explorium',
    name: 'Explorium',
    description: 'AI platform that automatically discovers and enriches datasets with external signals for better models.',
    category: 'Analytics',
    pricing: 'Paid',
    rating: 4.1,
    users: '3K+',
    features: ['Data enrichment', 'Signal discovery', 'AutoML', 'Feature engineering'],
  },
  {
    id: 'hex-ai',
    name: 'Hex AI',
    description: 'AI-powered data workspace combining notebooks, SQL, and apps for collaborative analytics.',
    category: 'Analytics',
    pricing: 'Freemium',
    rating: 4.5,
    users: '100K+',
    features: ['Notebook + SQL', 'AI magic', 'App publishing', 'Team collaboration'],
  },
  {
    id: 'tellius',
    name: 'Tellius',
    description: 'Decision intelligence platform using AI to automatically find drivers behind business metrics.',
    category: 'Analytics',
    pricing: 'Paid',
    rating: 4.2,
    users: '2K+',
    features: ['Driver analysis', 'Natural language queries', 'Auto insights', 'Smart alerts'],
  },
  {
    id: 'sigma-computing',
    name: 'Sigma AI',
    description: 'Cloud analytics tool with AI features that lets business users explore data in a spreadsheet-like UI.',
    category: 'Analytics',
    pricing: 'Paid',
    rating: 4.3,
    users: '30K+',
    features: ['Spreadsheet UI', 'AI insights', 'Live data', 'Collaboration'],
  },
  {
    id: 'answerrocket',
    name: 'AnswerRocket',
    description: 'AI search-driven analytics where users ask data questions in plain English and get instant answers.',
    category: 'Analytics',
    pricing: 'Paid',
    rating: 4.0,
    users: '10K+',
    features: ['NL queries', 'Auto charts', 'AI narratives', 'CRM integration'],
  },
  {
    id: 'row-zero',
    name: 'Row Zero',
    description: 'AI-powered spreadsheet built for big data, handling millions of rows with Python and SQL support.',
    category: 'Analytics',
    pricing: 'Freemium',
    rating: 4.2,
    users: '15K+',
    features: ['Big data sheets', 'Python/SQL', 'AI formulas', 'Live connections'],
  },

  // ── Marketing ─────────────────────────────────────────────────────────────
  {
    id: 'albert-ai',
    name: 'Albert AI',
    description: 'Autonomous AI marketing platform that plans, executes, and optimises paid digital campaigns.',
    category: 'Marketing',
    pricing: 'Paid',
    rating: 4.2,
    users: '5K+',
    features: ['Autonomous campaigns', 'Cross-channel', 'Budget optimisation', 'Audience insights'],
  },
  {
    id: 'persado',
    name: 'Persado',
    description: 'AI platform that generates and A/B tests emotional marketing language to maximise engagement.',
    category: 'Marketing',
    pricing: 'Paid',
    rating: 4.3,
    users: '3K+',
    features: ['Emotional AI', 'Language testing', 'Personalisation', 'Enterprise scale'],
  },
  {
    id: 'phrasee',
    name: 'Phrasee',
    description: 'AI content optimisation platform that generates and tests brand-compliant email and push copy.',
    category: 'Marketing',
    pricing: 'Paid',
    rating: 4.2,
    users: '2K+',
    features: ['Email subject lines', 'Push notifications', 'A/B testing', 'Brand voice'],
  },
  {
    id: 'adcreative-ai',
    name: 'AdCreative.ai',
    description: 'AI ad creative generator that produces conversion-optimised banner ads and social creatives.',
    category: 'Marketing',
    pricing: 'Paid',
    rating: 4.4,
    users: '500K+',
    features: ['Ad generation', 'Creative scoring', 'Brand kit', 'Platform templates'],
  },
  {
    id: 'marketing-muse',
    name: 'MarketMuse',
    description: 'AI content intelligence platform that plans content strategy and optimises pages for topical authority.',
    category: 'Marketing',
    pricing: 'Freemium',
    rating: 4.3,
    users: '10K+',
    features: ['Content planning', 'Topic modelling', 'Competitive analysis', 'SEO scoring'],
  },
  {
    id: 'surfer-seo',
    name: 'Surfer SEO',
    description: 'AI-driven SEO tool that analyses top-ranking pages and guides writers to create content that ranks.',
    category: 'Marketing',
    pricing: 'Paid',
    rating: 4.5,
    users: '150K+',
    features: ['Content editor', 'SERP analyser', 'Keyword research', 'AI outline'],
  },
  {
    id: 'seventh-sense',
    name: 'Seventh Sense',
    description: 'AI email send-time optimisation tool that delivers each message when each contact is most likely to open.',
    category: 'Marketing',
    pricing: 'Paid',
    rating: 4.1,
    users: '5K+',
    features: ['Send-time AI', 'HubSpot integration', 'Marketo integration', 'Deliverability'],
  },
  {
    id: 'socialbee-ai',
    name: 'SocialBee AI',
    description: 'Social media management platform with AI post generation and scheduling across all major channels.',
    category: 'Marketing',
    pricing: 'Paid',
    rating: 4.3,
    users: '50K+',
    features: ['AI post writer', 'Content calendar', 'Category scheduling', 'Analytics'],
  },
  {
    id: 'predis-ai',
    name: 'Predis AI',
    description: 'AI social media tool that generates complete posts with captions, hashtags, and matching visuals.',
    category: 'Marketing',
    pricing: 'Freemium',
    rating: 4.3,
    users: '300K+',
    features: ['Caption writing', 'Visual generation', 'Competitor analysis', 'Bulk scheduling'],
  },
  {
    id: 'smartly-io',
    name: 'Smartly',
    description: 'AI-powered social advertising platform for automating creative production and campaign management.',
    category: 'Marketing',
    pricing: 'Paid',
    rating: 4.4,
    users: '700+',
    features: ['Creative automation', 'Dynamic ads', 'Budget AI', 'Multi-channel'],
  },
  {
    id: 'semrush-ai',
    name: 'SEMrush ContentShake',
    description: 'AI writing tool inside SEMrush that generates SEO-ready articles from keyword research data.',
    category: 'Marketing',
    pricing: 'Paid',
    rating: 4.4,
    users: '1M+',
    features: ['SEO articles', 'Keyword integration', 'Readability scoring', 'One-click publish'],
  },
  {
    id: 'brand24',
    name: 'Brand24 AI',
    description: 'AI media monitoring tool that tracks brand mentions and analyses sentiment across the web.',
    category: 'Marketing',
    pricing: 'Paid',
    rating: 4.4,
    users: '4K+',
    features: ['Mention tracking', 'Sentiment analysis', 'Influencer scoring', 'Report generation'],
  },

  // ── Productivity ──────────────────────────────────────────────────────────
  {
    id: 'otter-ai',
    name: 'Otter.ai',
    description: 'AI meeting assistant that transcribes, summarises, and generates action items from voice conversations.',
    category: 'Productivity',
    pricing: 'Freemium',
    rating: 4.4,
    users: '15M+',
    features: ['Live transcription', 'AI summaries', 'Action items', 'Zoom integration'],
  },
  {
    id: 'fireflies-ai',
    name: 'Fireflies.ai',
    description: 'AI notetaker that records meetings, creates transcripts, and surfaces key moments automatically.',
    category: 'Productivity',
    pricing: 'Freemium',
    rating: 4.5,
    users: '300K+',
    features: ['Meeting recording', 'Smart search', 'CRM sync', 'Topic tracking'],
  },
  {
    id: 'reclaim-ai',
    name: 'Reclaim AI',
    description: 'AI calendar assistant that automatically schedules tasks, habits, and focus time around meetings.',
    category: 'Productivity',
    pricing: 'Freemium',
    rating: 4.5,
    users: '100K+',
    features: ['Smart scheduling', 'Habit blocks', 'Buffer time', 'Google Calendar sync'],
  },
  {
    id: 'mem-ai',
    name: 'Mem',
    description: 'AI-powered note-taking app that automatically organises notes and surfaces relevant information.',
    category: 'Productivity',
    pricing: 'Freemium',
    rating: 4.2,
    users: '100K+',
    features: ['Auto-organisation', 'Smart search', 'AI writing', 'Bi-directional links'],
  },
  {
    id: 'superhuman',
    name: 'Superhuman AI',
    description: 'Blazing-fast email client with AI to draft replies, triage inboxes, and reach inbox zero daily.',
    category: 'Productivity',
    pricing: 'Paid',
    rating: 4.6,
    users: '150K+',
    features: ['AI draft', 'Triage', 'Read statuses', 'Shortcuts-first'],
  },
  {
    id: 'taskade',
    name: 'Taskade AI',
    description: 'AI productivity workspace combining tasks, docs, and chat with AI agents for team collaboration.',
    category: 'Productivity',
    pricing: 'Freemium',
    rating: 4.4,
    users: '500K+',
    features: ['AI agents', 'Task management', 'Mind maps', 'Video chat'],
  },
  {
    id: 'tldv',
    name: 'tl;dv',
    description: 'AI meeting recorder for Zoom and Google Meet that timestamps key moments and generates summaries.',
    category: 'Productivity',
    pricing: 'Freemium',
    rating: 4.5,
    users: '300K+',
    features: ['Meeting clips', 'Summaries', 'Timestamps', 'CRM integration'],
  },
  {
    id: 'magical-ai',
    name: 'Magical AI',
    description: 'AI text expander and automation tool that drafts messages and auto-fills forms across any website.',
    category: 'Productivity',
    pricing: 'Freemium',
    rating: 4.3,
    users: '500K+',
    features: ['Text expansion', 'Auto-fill', 'AI drafting', 'Browser extension'],
  },
  {
    id: 'cogram',
    name: 'Cogram',
    description: 'AI assistant for project teams that writes meeting minutes and tracks decisions and follow-ups.',
    category: 'Productivity',
    pricing: 'Paid',
    rating: 4.2,
    users: '10K+',
    features: ['Meeting minutes', 'Decision tracking', 'Follow-ups', 'Slack integration'],
  },
  {
    id: 'ai-email-writer',
    name: 'Lavender',
    description: 'AI email coach that scores outbound sales emails in real time and suggests improvements to boost replies.',
    category: 'Productivity',
    pricing: 'Freemium',
    rating: 4.5,
    users: '50K+',
    features: ['Email scoring', 'Personalisation', 'Mobile preview', 'CRM integration'],
  },
  {
    id: 'raycast-ai',
    name: 'Raycast AI',
    description: 'Launcher app for Mac with built-in AI assistant for instant answers, drafts, and code snippets.',
    category: 'Productivity',
    pricing: 'Freemium',
    rating: 4.7,
    users: '200K+',
    features: ['Spotlight replacement', 'AI commands', 'Extensions', 'Snippets'],
  },
  {
    id: 'capacities-ai',
    name: 'Capacities',
    description: 'AI-powered personal knowledge management studio that links notes, bookmarks, and ideas together.',
    category: 'Productivity',
    pricing: 'Freemium',
    rating: 4.3,
    users: '50K+',
    features: ['Object-based notes', 'AI writing', 'Graph view', 'Daily notes'],
  },

  // ── Image Generation ──────────────────────────────────────────────────────
  {
    id: 'dalle3',
    name: 'DALL·E 3',
    description: 'OpenAI\'s image generation model with exceptional prompt adherence, integrated into ChatGPT.',
    category: 'Image Generation',
    pricing: 'Freemium',
    rating: 4.7,
    users: '50M+',
    features: ['Prompt accuracy', 'Text in images', 'ChatGPT integration', 'Safety filtering'],
  },
  {
    id: 'ideogram',
    name: 'Ideogram',
    description: 'AI image generator with best-in-class text rendering inside generated images.',
    category: 'Image Generation',
    pricing: 'Freemium',
    rating: 4.5,
    users: '2M+',
    features: ['Text in images', 'Poster design', 'Style presets', 'Remix'],
  },
  {
    id: 'playground-ai',
    name: 'Playground AI',
    description: 'Consumer-friendly AI image generator with a generous free tier and a real-time canvas editor.',
    category: 'Image Generation',
    pricing: 'Freemium',
    rating: 4.4,
    users: '5M+',
    features: ['Canvas editor', 'Inpainting', 'Style mix', 'Community gallery'],
  },
  {
    id: 'nightcafe',
    name: 'NightCafe Creator',
    description: 'AI art generator with multiple algorithms, a credits system, and a vibrant creator community.',
    category: 'Image Generation',
    pricing: 'Freemium',
    rating: 4.3,
    users: '8M+',
    features: ['Multi-algorithm', 'Community', 'Prints', 'Daily challenges'],
  },
  {
    id: 'leonardo-ai',
    name: 'Leonardo AI',
    description: 'AI image generation platform for game assets, concept art, and creative production at scale.',
    category: 'Image Generation',
    pricing: 'Freemium',
    rating: 4.6,
    users: '4M+',
    features: ['Custom models', 'Image to image', 'Canvas', 'API access'],
  },
  {
    id: 'firefly-ai',
    name: 'Firefly Image 3',
    description: 'Adobe\'s latest AI image model offering commercially safe, photorealistic image generation.',
    category: 'Image Generation',
    pricing: 'Freemium',
    rating: 4.6,
    users: '10M+',
    features: ['Commercial safe', 'Photorealistic', 'Structure reference', 'Style reference'],
  },
  {
    id: 'getimg-ai',
    name: 'getimg.ai',
    description: 'Suite of AI image tools including generation, editing, expansion, and face restoration.',
    category: 'Image Generation',
    pricing: 'Freemium',
    rating: 4.3,
    users: '1M+',
    features: ['20+ models', 'Inpainting', 'Outpainting', 'Face restoration'],
  },
  {
    id: 'pika-labs',
    name: 'Pika Labs',
    description: 'AI image generation with a focus on anime, illustration, and stylised artwork from text prompts.',
    category: 'Image Generation',
    pricing: 'Freemium',
    rating: 4.2,
    users: '500K+',
    features: ['Anime styles', 'Text prompts', 'Discord bot', 'Community'],
  },
  {
    id: 'tensor-art',
    name: 'Tensor.Art',
    description: 'AI image platform hosting thousands of community models for virtually any image style.',
    category: 'Image Generation',
    pricing: 'Freemium',
    rating: 4.2,
    users: '2M+',
    features: ['Model marketplace', 'LoRA training', 'Workflow builder', 'API'],
  },
  {
    id: 'seaart',
    name: 'SeaArt AI',
    description: 'AI art generator with a built-in studio, character consistency tools, and model fine-tuning.',
    category: 'Image Generation',
    pricing: 'Freemium',
    rating: 4.1,
    users: '3M+',
    features: ['Character consistency', 'Fine-tuning', 'Inpainting', 'Video generation'],
  },
  {
    id: 'artbreeder',
    name: 'Artbreeder',
    description: 'Generative AI tool that blends and evolves images collaboratively using GANs.',
    category: 'Image Generation',
    pricing: 'Freemium',
    rating: 4.1,
    users: '10M+',
    features: ['Image blending', 'Character portraits', 'Landscape creation', 'Collage tool'],
  },
  {
    id: 'clipdrop',
    name: 'Clipdrop',
    description: 'Stability AI\'s suite of image editing APIs including background removal, upscaling, and relighting.',
    category: 'Image Generation',
    pricing: 'Freemium',
    rating: 4.4,
    users: '15M+',
    features: ['Relight', 'Upscale', 'Background removal', 'Uncrop'],
  },

  // ── Video ─────────────────────────────────────────────────────────────────
  {
    id: 'sora',
    name: 'Sora',
    description: 'OpenAI\'s text-to-video model that generates cinematic, physics-aware video clips from prompts.',
    category: 'Video',
    pricing: 'Paid',
    rating: 4.6,
    users: '1M+',
    features: ['Text-to-video', 'Cinematic quality', 'Long clips', 'Storyboard'],
  },
  {
    id: 'kling-ai',
    name: 'Kling AI',
    description: 'High-fidelity text-to-video and image-to-video generator from Kuaishou with 2-minute clip support.',
    category: 'Video',
    pricing: 'Freemium',
    rating: 4.5,
    users: '5M+',
    features: ['2-min clips', 'Image-to-video', 'Motion control', 'Lip sync'],
  },
  {
    id: 'luma-dream-machine',
    name: 'Luma Dream Machine',
    description: 'Fast AI video generation model producing smooth, realistic clips from text and images.',
    category: 'Video',
    pricing: 'Freemium',
    rating: 4.4,
    users: '2M+',
    features: ['Fast generation', 'Image-to-video', 'Smooth motion', 'Loop creation'],
  },
  {
    id: 'heygen',
    name: 'HeyGen',
    description: 'AI video platform for creating personalised talking-head videos with realistic voice and avatar sync.',
    category: 'Video',
    pricing: 'Freemium',
    rating: 4.6,
    users: '500K+',
    features: ['Avatar videos', 'Voice cloning', 'Video translation', 'Personalisation'],
  },
  {
    id: 'descript',
    name: 'Descript',
    description: 'AI-powered video and podcast editor that lets you edit media by editing the transcript.',
    category: 'Video',
    pricing: 'Freemium',
    rating: 4.5,
    users: '3M+',
    features: ['Transcript editing', 'Overdub voice', 'Screen recording', 'Filler word removal'],
  },
  {
    id: 'captions-ai',
    name: 'Captions AI',
    description: 'AI video studio for creators featuring auto-captions, eye contact correction, and AI b-roll.',
    category: 'Video',
    pricing: 'Freemium',
    rating: 4.4,
    users: '7M+',
    features: ['Auto-captions', 'Eye contact AI', 'AI b-roll', 'Creator templates'],
  },
  {
    id: 'invideo-ai',
    name: 'InVideo AI',
    description: 'AI video creation platform that turns a text prompt into a fully edited, narrated video.',
    category: 'Video',
    pricing: 'Freemium',
    rating: 4.3,
    users: '7M+',
    features: ['Text-to-video', 'Voiceover', 'Stock media', 'Template library'],
  },
  {
    id: 'pictory-ai',
    name: 'Pictory',
    description: 'AI video tool that converts long-form blog posts and scripts into short, shareable social videos.',
    category: 'Video',
    pricing: 'Paid',
    rating: 4.3,
    users: '800K+',
    features: ['Blog-to-video', 'Auto-highlights', 'Captions', 'Stock footage'],
  },
  {
    id: 'fliki-ai',
    name: 'Fliki',
    description: 'AI video and voiceover creator with 2,000+ realistic voices in 75 languages.',
    category: 'Video',
    pricing: 'Freemium',
    rating: 4.3,
    users: '2M+',
    features: ['2000+ voices', '75 languages', 'Text-to-video', 'Stock media'],
  },
  {
    id: 'opus-clip',
    name: 'Opus Clip',
    description: 'AI repurposing tool that finds the most engaging moments in long videos and turns them into viral shorts.',
    category: 'Video',
    pricing: 'Freemium',
    rating: 4.5,
    users: '2M+',
    features: ['AI clipping', 'Virality score', 'Auto-captions', 'Multi-platform'],
  },
  {
    id: 'visla',
    name: 'Visla',
    description: 'AI video platform for enterprise teams to create training, marketing, and communications videos fast.',
    category: 'Video',
    pricing: 'Freemium',
    rating: 4.2,
    users: '200K+',
    features: ['Screen recording', 'Stock footage AI', 'Team workspace', 'Sharing'],
  },
  {
    id: 'waymark',
    name: 'Waymark',
    description: 'AI video maker for local businesses that creates broadcast-quality ads in minutes from a URL.',
    category: 'Video',
    pricing: 'Paid',
    rating: 4.2,
    users: '30K+',
    features: ['URL-to-video', 'Broadcast quality', 'Voiceover', 'Brand scanning'],
  },

  // ── Audio ─────────────────────────────────────────────────────────────────
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    description: 'Ultra-realistic AI voice synthesis and cloning platform used by creators, publishers, and enterprises.',
    category: 'Audio',
    pricing: 'Freemium',
    rating: 4.8,
    users: '1M+',
    features: ['Voice cloning', 'Emotional speech', '29 languages', 'API access'],
  },
  {
    id: 'suno-ai',
    name: 'Suno',
    description: 'AI music generator that creates original, full songs with vocals and instruments from a text prompt.',
    category: 'Audio',
    pricing: 'Freemium',
    rating: 4.6,
    users: '10M+',
    features: ['Full song generation', 'Lyrics writing', 'Genre control', 'Custom styles'],
  },
  {
    id: 'udio-ai',
    name: 'Udio',
    description: 'AI music creation platform with granular style controls for producing high-quality original tracks.',
    category: 'Audio',
    pricing: 'Freemium',
    rating: 4.5,
    users: '2M+',
    features: ['Music generation', 'Style mixing', 'Lyrics input', 'Remix mode'],
  },
  {
    id: 'aiva',
    name: 'AIVA',
    description: 'AI composer that writes original orchestral and cinematic music for films, games, and ads.',
    category: 'Audio',
    pricing: 'Freemium',
    rating: 4.4,
    users: '300K+',
    features: ['Orchestral AI', 'Royalty-free', 'DAW export', 'Style presets'],
  },
  {
    id: 'adobe-podcast',
    name: 'Adobe Podcast AI',
    description: 'AI audio tools from Adobe for enhancing speech quality and removing background noise from recordings.',
    category: 'Audio',
    pricing: 'Freemium',
    rating: 4.5,
    users: '5M+',
    features: ['Speech enhancement', 'Noise removal', 'Mic match', 'Studio quality'],
  },
  {
    id: 'krisp',
    name: 'Krisp',
    description: 'AI noise-cancellation app that removes background sounds, voices, and echo from any call.',
    category: 'Audio',
    pricing: 'Freemium',
    rating: 4.6,
    users: '4M+',
    features: ['Background noise removal', 'Echo cancellation', 'Meeting transcription', 'Works with any app'],
  },
  {
    id: 'resemble-ai',
    name: 'Resemble AI',
    description: 'AI voice platform for building custom neural voice clones with real-time generation capabilities.',
    category: 'Audio',
    pricing: 'Paid',
    rating: 4.3,
    users: '10K+',
    features: ['Real-time cloning', 'Emotion control', 'API access', 'Watermarking'],
  },
  {
    id: 'speechify',
    name: 'Speechify',
    description: 'AI text-to-speech reader that converts any text into natural-sounding audio at up to 4.5× speed.',
    category: 'Audio',
    pricing: 'Freemium',
    rating: 4.5,
    users: '20M+',
    features: ['Speed reading', 'Celebrity voices', 'OCR scan', 'Cross-device sync'],
  },
  {
    id: 'lalal-ai',
    name: 'LALAL.AI',
    description: 'AI stem splitter that separates vocals, instruments, and sounds from audio tracks with high accuracy.',
    category: 'Audio',
    pricing: 'Freemium',
    rating: 4.5,
    users: '1M+',
    features: ['Vocal removal', 'Stem splitting', 'Batch processing', 'API'],
  },
  {
    id: 'soundraw',
    name: 'Soundraw',
    description: 'AI royalty-free music generator for creators, offering customisable length, mood, and instrumentation.',
    category: 'Audio',
    pricing: 'Paid',
    rating: 4.4,
    users: '500K+',
    features: ['Mood selection', 'Length control', 'Royalty-free', 'Customisable'],
  },
  {
    id: 'beatoven-ai',
    name: 'Beatoven.ai',
    description: 'AI background music creator that generates unique, royalty-free tracks tailored to video mood.',
    category: 'Audio',
    pricing: 'Freemium',
    rating: 4.2,
    users: '200K+',
    features: ['Mood-based music', 'Video sync', 'Royalty-free', 'Genre selection'],
  },
  {
    id: 'podcastle',
    name: 'Podcastle',
    description: 'AI podcast studio offering recording, transcription, voice enhancement, and video repurposing.',
    category: 'Audio',
    pricing: 'Freemium',
    rating: 4.3,
    users: '500K+',
    features: ['Remote recording', 'AI enhancement', 'Transcription', 'Text-to-speech'],
  },

  // ── Chatbots ──────────────────────────────────────────────────────────────
  {
    id: 'manychat',
    name: 'ManyChat',
    description: 'Visual chatbot builder for Instagram, Facebook, and WhatsApp with AI-powered conversation flows.',
    category: 'Chatbots',
    pricing: 'Freemium',
    rating: 4.5,
    users: '1M+',
    features: ['Visual builder', 'Instagram DMs', 'Broadcast messages', 'E-commerce flows'],
  },
  {
    id: 'chatfuel',
    name: 'Chatfuel',
    description: 'AI chatbot platform for WhatsApp and Instagram that automates sales and support conversations.',
    category: 'Chatbots',
    pricing: 'Freemium',
    rating: 4.3,
    users: '500K+',
    features: ['WhatsApp chatbot', 'GPT integration', 'Broadcast', 'Ecommerce'],
  },
  {
    id: 'landbot',
    name: 'Landbot',
    description: 'No-code chatbot builder for creating conversational landing pages and lead generation flows.',
    category: 'Chatbots',
    pricing: 'Freemium',
    rating: 4.3,
    users: '100K+',
    features: ['No-code builder', 'Conversational forms', 'WhatsApp bot', 'Integrations'],
  },
  {
    id: 'botpress',
    name: 'Botpress',
    description: 'Open-source AI chatbot platform with an autonomous AI agent builder for enterprise deployments.',
    category: 'Chatbots',
    pricing: 'Freemium',
    rating: 4.4,
    users: '50K+',
    features: ['Open source', 'LLM-powered', 'Multi-channel', 'Visual studio'],
  },
  {
    id: 'voiceflow',
    name: 'Voiceflow',
    description: 'Collaborative platform for designing and deploying AI agents and chatbots across any channel.',
    category: 'Chatbots',
    pricing: 'Freemium',
    rating: 4.5,
    users: '200K+',
    features: ['Agent design', 'KB integration', 'Multi-channel', 'Analytics'],
  },
  {
    id: 'drift',
    name: 'Drift AI',
    description: 'Conversational marketing platform with AI chatbots that qualify leads and book meetings automatically.',
    category: 'Chatbots',
    pricing: 'Paid',
    rating: 4.3,
    users: '50K+',
    features: ['Lead qualification', 'Meeting booking', 'CRM sync', 'Personalisation'],
  },
  {
    id: 'yellow-ai',
    name: 'Yellow.ai',
    description: 'Enterprise-grade AI chatbot and voice bot platform with omnichannel deployment capabilities.',
    category: 'Chatbots',
    pricing: 'Paid',
    rating: 4.2,
    users: '1K+',
    features: ['Omnichannel', 'Voice bots', 'Sentiment AI', 'NLP training'],
  },
  {
    id: 'rasa',
    name: 'Rasa',
    description: 'Open-source conversational AI framework for building customisable enterprise chatbots with full data control.',
    category: 'Chatbots',
    pricing: 'Freemium',
    rating: 4.2,
    users: '100K+',
    features: ['Open source', 'On-premise', 'Custom NLU', 'Multi-turn dialogue'],
  },
  {
    id: 'instabot',
    name: 'Collect.chat',
    description: 'Drag-and-drop chatbot builder for lead capture and surveys with conditional logic and scheduling.',
    category: 'Chatbots',
    pricing: 'Freemium',
    rating: 4.0,
    users: '15K+',
    features: ['Lead capture', 'Conditional logic', 'Calendar booking', 'Zapier integration'],
  },
  {
    id: 'cohere-coral',
    name: 'Cohere Coral',
    description: 'Enterprise AI assistant powered by Cohere\'s models with grounded, citation-backed answers from internal docs.',
    category: 'Chatbots',
    pricing: 'Paid',
    rating: 4.3,
    users: '5K+',
    features: ['RAG-powered', 'Source citations', 'Enterprise security', 'Custom models'],
  },
  {
    id: 'sendbird-ai',
    name: 'Sendbird AI Chatbot',
    description: 'AI chatbot builder for in-app messaging, enabling brands to deploy GPT-powered bots inside their products.',
    category: 'Chatbots',
    pricing: 'Paid',
    rating: 4.2,
    users: '10K+',
    features: ['In-app chatbot', 'GPT-4 powered', 'SDK integration', 'Analytics'],
  },
  {
    id: 'haptik',
    name: 'Haptik',
    description: 'Jio Haptik\'s enterprise conversational AI platform for WhatsApp, web, and IVR automation.',
    category: 'Chatbots',
    pricing: 'Paid',
    rating: 4.1,
    users: '5K+',
    features: ['WhatsApp commerce', 'IVR automation', 'NLU engine', 'Analytics dashboard'],
  },

  // ── Research ──────────────────────────────────────────────────────────────
  {
    id: 'consensus-ai',
    name: 'Consensus',
    description: 'AI search engine for scientific research that surfaces consensus and disagreement across papers.',
    category: 'Research',
    pricing: 'Freemium',
    rating: 4.5,
    users: '2M+',
    features: ['Consensus meter', 'Paper summaries', 'Citation export', 'Study snapshots'],
  },
  {
    id: 'scite-ai',
    name: 'Scite',
    description: 'AI research assistant that shows how papers have been cited—whether supporting, contrasting, or mentioning.',
    category: 'Research',
    pricing: 'Freemium',
    rating: 4.4,
    users: '500K+',
    features: ['Citation context', 'Smart references', 'Search assistant', 'Journal metrics'],
  },
  {
    id: 'semantic-scholar',
    name: 'Semantic Scholar',
    description: 'Free AI-powered academic search engine with 220M+ papers, TL;DR summaries, and citation graphs.',
    category: 'Research',
    pricing: 'Free',
    rating: 4.5,
    users: '10M+',
    features: ['TL;DR summaries', 'Citation graphs', 'Influence score', 'Paper alerts'],
  },
  {
    id: 'research-rabbit',
    name: 'ResearchRabbit',
    description: 'Free AI tool that maps academic literature and suggests related papers from your reading list.',
    category: 'Research',
    pricing: 'Free',
    rating: 4.5,
    users: '400K+',
    features: ['Paper mapping', 'Collections', 'Related work', 'Zotero sync'],
  },
  {
    id: 'iris-ai',
    name: 'Iris.ai',
    description: 'AI research workspace for scientists that extracts, analyses, and connects insights across documents.',
    category: 'Research',
    pricing: 'Freemium',
    rating: 4.2,
    users: '100K+',
    features: ['Document upload', 'Key extract', 'Tech landscape', 'API'],
  },
  {
    id: 'connected-papers',
    name: 'Connected Papers',
    description: 'Visual tool to explore academic papers in graph form, revealing connections between related research.',
    category: 'Research',
    pricing: 'Freemium',
    rating: 4.4,
    users: '500K+',
    features: ['Paper graphs', 'Prior work', 'Derivative work', 'Bibliography export'],
  },
  {
    id: 'litmaps',
    name: 'Litmaps',
    description: 'AI-powered citation mapping tool that tracks how scientific knowledge evolves over time.',
    category: 'Research',
    pricing: 'Freemium',
    rating: 4.3,
    users: '100K+',
    features: ['Citation timelines', 'Alert system', 'Seed paper search', 'Team sharing'],
  },
  {
    id: 'scholarcy',
    name: 'Scholarcy',
    description: 'AI summarisation tool that breaks down research papers and textbooks into flashcard-style summaries.',
    category: 'Research',
    pricing: 'Freemium',
    rating: 4.2,
    users: '200K+',
    features: ['Article summaries', 'Flashcards', 'Reference extraction', 'Library'],
  },
  {
    id: 'explainpaper',
    name: 'Explainpaper',
    description: 'Upload any academic paper and use AI to explain confusing passages in plain language instantly.',
    category: 'Research',
    pricing: 'Freemium',
    rating: 4.3,
    users: '150K+',
    features: ['Passage explanation', 'PDF upload', 'Follow-up questions', 'History'],
  },
  {
    id: 'undermind-ai',
    name: 'Undermind',
    description: 'Deep AI research agent that conducts exhaustive academic searches and delivers curated, cited reports.',
    category: 'Research',
    pricing: 'Freemium',
    rating: 4.4,
    users: '20K+',
    features: ['Deep search', 'Full reports', 'Source tracing', 'Scope control'],
  },
  {
    id: 'jenni-ai',
    name: 'Jenni AI',
    description: 'AI writing assistant for researchers and students offering citations, paraphrasing, and academic templates.',
    category: 'Research',
    pricing: 'Freemium',
    rating: 4.3,
    users: '1M+',
    features: ['In-text citations', 'Paraphrase', 'AI autocomplete', 'PDF upload'],
  },
  {
    id: 'paperpal',
    name: 'Paperpal',
    description: 'AI academic writing tool by Researcher that improves manuscripts and checks scientific language.',
    category: 'Research',
    pricing: 'Freemium',
    rating: 4.2,
    users: '300K+',
    features: ['Academic editing', 'Language checks', 'Journal formatting', 'Submission-ready'],
  },

  // ── Education ─────────────────────────────────────────────────────────────
  {
    id: 'coursebox-ai',
    name: 'Coursebox',
    description: 'AI course creator that turns documents and videos into structured e-learning courses in minutes.',
    category: 'Education',
    pricing: 'Freemium',
    rating: 4.4,
    users: '50K+',
    features: ['Course generation', 'Quiz builder', 'AI tutor', 'White-label LMS'],
  },
  {
    id: 'synthesis-tutor',
    name: 'Synthesis Tutor',
    description: 'Adaptive AI math tutor for children that adjusts difficulty in real time based on performance.',
    category: 'Education',
    pricing: 'Paid',
    rating: 4.5,
    users: '200K+',
    features: ['Adaptive learning', 'Math focus', 'Progress tracking', 'Parent dashboard'],
  },
  {
    id: 'photomath',
    name: 'Photomath',
    description: 'AI camera calculator that scans handwritten or printed maths problems and shows step-by-step solutions.',
    category: 'Education',
    pricing: 'Freemium',
    rating: 4.7,
    users: '220M+',
    features: ['Camera scan', 'Step-by-step', 'Graph plotting', 'Word problems'],
  },
  {
    id: 'socratic-google',
    name: 'Socratic by Google',
    description: 'Google AI homework helper that scans questions and finds the best online explanations for students.',
    category: 'Education',
    pricing: 'Free',
    rating: 4.5,
    users: '50M+',
    features: ['Camera search', 'Step explanations', 'Subject coverage', 'Free forever'],
  },
  {
    id: 'quizlet-ai',
    name: 'Quizlet AI',
    description: 'AI-powered study tool that generates flashcards, practice tests, and explanations from any text.',
    category: 'Education',
    pricing: 'Freemium',
    rating: 4.6,
    users: '60M+',
    features: ['Auto flashcards', 'Practice tests', 'AI explanations', 'Study groups'],
  },
  {
    id: 'brainly-ai',
    name: 'Brainly',
    description: 'AI homework help community where students get step-by-step explanations from AI and peers.',
    category: 'Education',
    pricing: 'Freemium',
    rating: 4.3,
    users: '350M+',
    features: ['AI scanner', 'Step-by-step', 'Community answers', 'Multi-subject'],
  },
  {
    id: 'numerade',
    name: 'Numerade',
    description: 'STEM-focused AI tutor with thousands of video solutions and an AI study partner for hard problems.',
    category: 'Education',
    pricing: 'Freemium',
    rating: 4.3,
    users: '5M+',
    features: ['Video solutions', 'AI tutor', 'Textbook coverage', 'STEM focus'],
  },
  {
    id: 'wonders-learning',
    name: 'Kira',
    description: 'Personalised AI reading coach for K-8 students that adapts stories and comprehension questions to each child.',
    category: 'Education',
    pricing: 'Paid',
    rating: 4.4,
    users: '100K+',
    features: ['Adaptive stories', 'Reading level AI', 'Comprehension checks', 'Parent reports'],
  },
  {
    id: 'studyx',
    name: 'StudyX',
    description: 'AI homework solver and study assistant covering maths, science, history, and language arts.',
    category: 'Education',
    pricing: 'Freemium',
    rating: 4.2,
    users: '3M+',
    features: ['Multi-subject', 'Photo solver', 'AI tutor chat', 'Flashcard creator'],
  },
  {
    id: 'magic-school-ai',
    name: 'MagicSchool AI',
    description: 'AI platform built for teachers to generate lesson plans, rubrics, quizzes, and parent communications.',
    category: 'Education',
    pricing: 'Freemium',
    rating: 4.6,
    users: '3M+',
    features: ['Lesson plans', 'Rubric builder', 'Differentiation', 'IEP support'],
  },
  {
    id: 'conker-ai',
    name: 'Conker',
    description: 'AI quiz and worksheet generator for educators that creates assessments from any topic in seconds.',
    category: 'Education',
    pricing: 'Freemium',
    rating: 4.3,
    users: '200K+',
    features: ['Quiz generation', 'Worksheets', 'Google Forms export', 'Difficulty control'],
  },
  {
    id: 'curipod',
    name: 'Curipod',
    description: 'AI interactive lesson creator for teachers that generates slides, polls, and activities in one click.',
    category: 'Education',
    pricing: 'Freemium',
    rating: 4.4,
    users: '500K+',
    features: ['Interactive slides', 'AI activities', 'Student responses', 'Templates'],
  },

  // ── Customer Support ──────────────────────────────────────────────────────
  {
    id: 'kustomer-ai',
    name: 'Kustomer AI',
    description: 'CRM-native AI platform that provides agents with suggested replies and auto-resolves simple tickets.',
    category: 'Customer Support',
    pricing: 'Paid',
    rating: 4.3,
    users: '5K+',
    features: ['Auto-reply', 'CRM context', 'Sentiment AI', 'Omnichannel'],
  },
  {
    id: 'forethought-ai',
    name: 'Forethought',
    description: 'Generative AI platform for support teams that automates ticket resolution and assists human agents.',
    category: 'Customer Support',
    pricing: 'Paid',
    rating: 4.4,
    users: '3K+',
    features: ['Ticket automation', 'Agent assist', 'Intent detection', 'Salesforce integration'],
  },
  {
    id: 'ada-ai',
    name: 'Ada',
    description: 'AI customer service platform that automates over 70% of enquiries without human involvement.',
    category: 'Customer Support',
    pricing: 'Paid',
    rating: 4.3,
    users: '700+',
    features: ['70%+ automation', 'No-code builder', 'Multilingual', 'Coaching'],
  },
  {
    id: 'ultimate-ai',
    name: 'Ultimate',
    description: 'AI-powered customer support automation platform built for enterprise contact centres.',
    category: 'Customer Support',
    pricing: 'Paid',
    rating: 4.3,
    users: '1K+',
    features: ['Intent classification', 'Dialogue manager', 'Live agent handover', 'Zendesk integration'],
  },
  {
    id: 'aisera',
    name: 'Aisera',
    description: 'Generative AI platform for IT and HR service desks that automates employee and customer requests.',
    category: 'Customer Support',
    pricing: 'Paid',
    rating: 4.2,
    users: '5K+',
    features: ['IT service desk', 'HR automation', 'Conversational AI', 'ServiceNow integration'],
  },
  {
    id: 'netomi-ai',
    name: 'Netomi',
    description: 'AI customer service platform with an email, chat, and social automation engine for high-volume teams.',
    category: 'Customer Support',
    pricing: 'Paid',
    rating: 4.2,
    users: '2K+',
    features: ['Email AI', 'Chat AI', 'Social AI', 'Brand voice control'],
  },
  {
    id: 'yuma-ai',
    name: 'Yuma AI',
    description: 'AI ticket assistant purpose-built for Shopify merchants that auto-replies to order and shipping queries.',
    category: 'Customer Support',
    pricing: 'Paid',
    rating: 4.4,
    users: '5K+',
    features: ['Shopify native', 'Order lookup', 'Auto-draft', 'Gorgias integration'],
  },
  {
    id: 'gorgias-ai',
    name: 'Gorgias AI',
    description: 'E-commerce helpdesk with AI that auto-answers repetitive tickets and personalises responses from order data.',
    category: 'Customer Support',
    pricing: 'Paid',
    rating: 4.5,
    users: '12K+',
    features: ['E-commerce focus', 'One-click close', 'Revenue stats', 'Macro suggestions'],
  },
  {
    id: 'helpcenter-ai',
    name: 'HelpCenter.io',
    description: 'AI-powered knowledge base builder that auto-generates help articles from support ticket history.',
    category: 'Customer Support',
    pricing: 'Freemium',
    rating: 4.1,
    users: '10K+',
    features: ['Article generation', 'Ticket import', 'Search AI', 'Shopify app'],
  },
  {
    id: 'assembled-ai',
    name: 'Assembled',
    description: 'Workforce management platform for support teams with AI-powered scheduling and forecasting.',
    category: 'Customer Support',
    pricing: 'Paid',
    rating: 4.3,
    users: '300+',
    features: ['WFM forecasting', 'Staffing AI', 'Slack integration', 'Performance tracking'],
  },
  {
    id: 'parloa',
    name: 'Parloa',
    description: 'AI agent platform for voice and chat support that handles complex conversations end-to-end.',
    category: 'Customer Support',
    pricing: 'Paid',
    rating: 4.2,
    users: '500+',
    features: ['Voice AI', 'Complex dialogue', 'NLU', 'Contact centre integration'],
  },
  {
    id: 'siena-ai',
    name: 'Siena AI',
    description: 'Empathetic AI customer service agent for e-commerce brands handling returns, FAQs, and promotions.',
    category: 'Customer Support',
    pricing: 'Paid',
    rating: 4.4,
    users: '2K+',
    features: ['Empathy engine', 'Returns handling', 'Multi-channel', 'Brand voice'],
  },

  // ── Finance ───────────────────────────────────────────────────────────────
  {
    id: 'intuit-assist',
    name: 'Intuit Assist',
    description: 'AI financial assistant embedded in QuickBooks and TurboTax that surfaces insights and automates tasks.',
    category: 'Finance',
    pricing: 'Freemium',
    rating: 4.4,
    users: '7M+',
    features: ['Cash flow insights', 'Tax suggestions', 'Invoice automation', 'Bookkeeping'],
  },
  {
    id: 'planful-ai',
    name: 'Planful',
    description: 'AI-powered financial planning and analysis platform for continuous business planning.',
    category: 'Finance',
    pricing: 'Paid',
    rating: 4.3,
    users: '1K+',
    features: ['FP&A automation', 'Scenario planning', 'Consolidation', 'Reporting'],
  },
  {
    id: 'kavout',
    name: 'Kavout',
    description: 'AI investment platform that uses machine learning to rank stocks and generate alpha signals.',
    category: 'Finance',
    pricing: 'Paid',
    rating: 4.1,
    users: '5K+',
    features: ['Stock ranking', 'Alpha signals', 'Portfolio construction', 'Risk analysis'],
  },
  {
    id: 'alphasense',
    name: 'AlphaSense',
    description: 'AI market intelligence platform that searches earnings calls, filings, and news to surface investment insights.',
    category: 'Finance',
    pricing: 'Paid',
    rating: 4.5,
    users: '4K+',
    features: ['Earnings search', 'Sentiment analysis', 'Smart synonyms', 'Deal tracking'],
  },
  {
    id: 'kensho',
    name: 'Kensho',
    description: 'S&P Global AI analytics platform for financial institutions offering NLP and predictive analytics.',
    category: 'Finance',
    pricing: 'Paid',
    rating: 4.3,
    users: '2K+',
    features: ['Financial NLP', 'Event analytics', 'Data linking', 'API access'],
  },
  {
    id: 'trullion',
    name: 'Trullion',
    description: 'AI accounting platform for auditors and finance teams that extracts data from contracts and automates compliance.',
    category: 'Finance',
    pricing: 'Paid',
    rating: 4.2,
    users: '500+',
    features: ['Contract extraction', 'Lease accounting', 'Revenue recognition', 'Audit trail'],
  },
  {
    id: 'abe-ai',
    name: 'Abe AI',
    description: 'AI-powered conversational banking assistant helping users manage finances, budgets, and goals.',
    category: 'Finance',
    pricing: 'Paid',
    rating: 4.0,
    users: '1K+',
    features: ['Budget tracking', 'Savings goals', 'Spending insights', 'Bank integration'],
  },
  {
    id: 'docuphase',
    name: 'DocuPhase AI',
    description: 'AI AP automation tool that captures invoices, routes approvals, and syncs with ERPs automatically.',
    category: 'Finance',
    pricing: 'Paid',
    rating: 4.1,
    users: '2K+',
    features: ['Invoice capture', 'Approval routing', 'ERP sync', 'Audit trail'],
  },
  {
    id: 'infer-ai-finance',
    name: 'Infer',
    description: 'AI financial modelling tool that lets FP&A teams build predictive models with natural language.',
    category: 'Finance',
    pricing: 'Paid',
    rating: 4.2,
    users: '500+',
    features: ['NL modelling', 'Scenario analysis', 'Data connectors', 'Collaboration'],
  },
  {
    id: 'mosaic-tech',
    name: 'Mosaic',
    description: 'Strategic finance platform with AI features for real-time financial reporting and planning.',
    category: 'Finance',
    pricing: 'Paid',
    rating: 4.4,
    users: '300+',
    features: ['Real-time metrics', 'Headcount planning', 'Revenue forecasting', 'SaaS KPIs'],
  },
  {
    id: 'brex-ai',
    name: 'Brex AI',
    description: 'AI expense management assistant embedded in Brex that auto-codes receipts and flags policy violations.',
    category: 'Finance',
    pricing: 'Freemium',
    rating: 4.5,
    users: '30K+',
    features: ['Auto-code expenses', 'Policy enforcement', 'Receipt capture', 'Real-time spend'],
  },
  {
    id: 'vena-ai',
    name: 'Vena AI',
    description: 'AI-powered FP&A platform inside Excel that automates budgeting, forecasting, and what-if analysis.',
    category: 'Finance',
    pricing: 'Paid',
    rating: 4.3,
    users: '1K+',
    features: ['Excel-native', 'Budgeting AI', 'What-if scenarios', 'Consolidation'],
  },

  // ── Healthcare ─────────────────────────────────────────────────────────────
  {
    id: 'abridge',
    name: 'Abridge',
    description: 'AI medical documentation tool that listens to clinical conversations and generates accurate notes instantly.',
    category: 'Healthcare',
    pricing: 'Paid',
    rating: 4.7,
    users: '100K+',
    features: ['Ambient AI', 'EHR integration', 'HIPAA compliant', 'Real-time notes'],
  },
  {
    id: 'suki-ai',
    name: 'Suki AI',
    description: 'Voice-enabled AI assistant for clinicians that dictates and structures clinical notes within seconds.',
    category: 'Healthcare',
    pricing: 'Paid',
    rating: 4.6,
    users: '50K+',
    features: ['Voice dictation', 'Note structuring', 'EHR sync', 'Specialty templates'],
  },
  {
    id: 'tempus-ai',
    name: 'Tempus AI',
    description: 'AI platform for oncology that analyses genomic and clinical data to guide personalised cancer treatment.',
    category: 'Healthcare',
    pricing: 'Paid',
    rating: 4.5,
    users: '5K+',
    features: ['Genomic analysis', 'Treatment matching', 'Clinical insights', 'Real-world data'],
  },
  {
    id: 'paige-ai',
    name: 'Paige AI',
    description: 'FDA-cleared AI pathology tool that detects cancer in whole-slide tissue images with high accuracy.',
    category: 'Healthcare',
    pricing: 'Paid',
    rating: 4.6,
    users: '3K+',
    features: ['FDA cleared', 'Cancer detection', 'Pathology AI', 'Whole-slide imaging'],
  },
  {
    id: 'aidoc',
    name: 'Aidoc',
    description: 'AI radiology co-pilot that flags critical findings in CT scans and prioritises urgent cases for radiologists.',
    category: 'Healthcare',
    pricing: 'Paid',
    rating: 4.5,
    users: '20K+',
    features: ['CT triage', 'Critical alerts', 'PACS integration', 'FDA cleared'],
  },
  {
    id: 'wellframe',
    name: 'Wellframe',
    description: 'Digital health platform using AI to connect care managers with high-risk patients between visits.',
    category: 'Healthcare',
    pricing: 'Paid',
    rating: 4.2,
    users: '2M+',
    features: ['Care management', 'Patient engagement', 'Risk stratification', 'Secure messaging'],
  },
  {
    id: 'buoy-health',
    name: 'Buoy Health',
    description: 'AI symptom checker and triage tool that guides patients to the right level of care based on their symptoms.',
    category: 'Healthcare',
    pricing: 'Free',
    rating: 4.3,
    users: '5M+',
    features: ['Symptom checking', 'Care navigation', 'Insurance check', 'Free to use'],
  },
  {
    id: 'infermedica',
    name: 'Infermedica',
    description: 'AI-powered medical triage and symptom assessment API used by health systems and insurers.',
    category: 'Healthcare',
    pricing: 'Paid',
    rating: 4.4,
    users: '10M+',
    features: ['Symptom API', 'Interview engine', 'Condition probability', 'Multi-language'],
  },
  {
    id: 'corti-ai',
    name: 'Corti',
    description: 'Real-time AI for emergency call centres that listens to calls and assists dispatchers in diagnosing patients.',
    category: 'Healthcare',
    pricing: 'Paid',
    rating: 4.5,
    users: '5K+',
    features: ['Emergency triage', 'Real-time assistance', 'Dispatcher support', 'Quality audit'],
  },
  {
    id: 'nabla-copilot',
    name: 'Nabla Copilot',
    description: 'Ambient AI medical scribe that turns patient conversations into structured clinical notes for physicians.',
    category: 'Healthcare',
    pricing: 'Freemium',
    rating: 4.6,
    users: '50K+',
    features: ['Ambient documentation', 'SOAP notes', 'EHR export', 'Multi-specialty'],
  },
  {
    id: 'viz-ai',
    name: 'Viz.ai',
    description: 'AI care coordination platform that detects stroke and critical conditions in imaging and alerts care teams.',
    category: 'Healthcare',
    pricing: 'Paid',
    rating: 4.5,
    users: '1K+',
    features: ['Stroke detection', 'Care coordination', 'Mobile alerts', 'FDA cleared'],
  },
  {
    id: 'regard-ai',
    name: 'Regard',
    description: 'AI clinical decision support tool that reads the EHR and surfaces missed diagnoses and billing opportunities.',
    category: 'Healthcare',
    pricing: 'Paid',
    rating: 4.4,
    users: '10K+',
    features: ['Diagnosis suggestions', 'CDI', 'EHR integration', 'Billing optimisation'],
  },
];
